apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: pod-lister
  name: pod-lister
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: pod-lister
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: pod-lister
    spec:
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: seanturner83/client-go-example:0.2@sha256:e5ba6eac956bec68f29f99e4827822e290f8fefa8867be790f6c0056ae80a374
        imagePullPolicy: Always
        name: pod-lister
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 300m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: pod-lister
      serviceAccountName: pod-lister
      terminationGracePeriodSeconds: 30
